### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by michaelrommel** [0oAstro/silicon.lua#29]
Dear Astro,

I have developed a plugin similar to yours last year. I did not know that yours exist. One of my users made me aware of a functionality that your plugins has: the generation of themes.

Without a license file, I do not know, if I can take inspiration from your code and create similar functionality for my plugin.

Would you mind to add a LICENSE file or otherwise indicate the license of your code in Github?

Thanks very much,

  Michael.

**Comment by 0oAstro** [comment]
Hey, first of all, great work man :)

Absolutely love it when I just hack up something and the community makes a polished and way less buggy version (same with dim.lua)

Umm... so as you can see I am MIA for quite a while and all my projects are pretty much abandoned at this point.

Feel free to take inspiration from the code. I will add the MIT LICENSE.
